language: python
python:
    - "3.7"
sudo: false
cache:
    directories:
        - "~/.platformio"
        - $HOME/.cache/pip
env:
    - PLATFORMIO_CI_SRC=Arduino/ESPNow_WT32_ETH01
install:
    - pip install -U platformio
    - platformio update
script:
    - platformio ci --project-conf=./platformio.ini -v